"""Miscellaneous activities: update_sermon, AI detection, content summary, RSS download."""

import json
import os

from activities.helpers import _openai_client, _cosmos_client
from log import log


def update_sermon(input_data):
    """Patch a sermon document in Cosmos DB with etag check."""
    container = _cosmos_client()
    sermon_id = input_data["sermonId"]
    updates = input_data["updates"]

    try:
        doc = container.read_item(sermon_id, partition_key=sermon_id)
    except Exception as e:
        if "NotFound" in type(e).__name__ or "CosmosResourceNotFoundError" in type(e).__name__:
            log.error(f"[update_sermon] {sermon_id}: not found in Cosmos")
            return {"ok": False, "error": "not_found"}
        raise

    etag = doc.get("_etag")
    doc.update(updates)

    try:
        kwargs = {}
        if etag:
            from azure.core import MatchConditions
            kwargs["etag"] = etag
            kwargs["match_condition"] = MatchConditions.IfNotModified
        container.upsert_item(doc, **kwargs)
    except Exception as e:
        if "PreconditionFailed" in type(e).__name__ or "412" in str(e):
            log.warning(f"[update_sermon] {sermon_id}: etag mismatch, re-reading and retrying")
            doc = container.read_item(sermon_id, partition_key=sermon_id)
            doc.update(updates)
            container.upsert_item(doc)
        else:
            raise

    return {"ok": True}


def detect_ai_generation(input_data):
    """Detect if transcript was AI-generated. Returns {"aiScore": 1|2|3, "aiReasoning": str}."""
    client = _openai_client()
    transcript = input_data["transcript"]
    words = transcript.split()
    sample = " ".join(words[:3000]) if len(words) > 3000 else transcript

    resp = client.chat.completions.create(
        model="gpt-5-nano",
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": "You are an AI-generated text detector analyzing sermon transcripts."},
            {"role": "user", "content": f"""Analyze this sermon transcript and determine if it was likely written/generated by AI or spoken/written by a human.

IMPORTANT CONTEXT: This may be a transcription of spoken audio OR a written manuscript. Written sermons (including historical ones like Spurgeon, Edwards, Lloyd-Jones) will naturally lack filler words and self-corrections — that does NOT make them AI-generated. Judge based on the signals below, not merely the absence of speech disfluencies.

SIGNALS OF AI-GENERATED TEXT (look for multiple):
- Formulaic structure: "First... Second... Third... Finally..." with unnaturally even section lengths
- Generic theological language that could apply to any sermon ("profound depths", "beloved congregation", "let us consider")
- Lack of distinctive pastoral voice — no personal conviction, no unique phrasing, no memorable turns of phrase
- Unnaturally balanced: every point gets equal treatment, no passion or emphasis on any particular truth
- Smooth, predictable transitions with no surprising connections or insights
- Absence of specific illustrations, personal stories, or concrete examples
- Perfect grammar throughout with no stylistic quirks or personality

SIGNALS OF HUMAN AUTHORSHIP (look for any):
- Distinctive voice and style (archaic language, regional expressions, unique metaphors)
- Genuine passion or conviction that builds unevenly — some points get more emphasis
- Specific illustrations from real life, history, or personal experience
- Audience awareness (direct address, rhetorical questions, humor, emotional appeals)
- Filler words, self-corrections, tangents (in transcribed speech)
- Uneven pacing — some sections dense, others more relaxed
- Strong opinions or convictions stated boldly

CRITICAL: A polished, literary sermon by a skilled human preacher (Spurgeon, Edwards, Keller) should score 1. Polish ≠ AI. The key differentiator is DISTINCTIVE VOICE and GENUINE CONVICTION vs GENERIC FORMULAIC output.

Return JSON:
{{"score": <1|2|3>, "reasoning": "<2-3 sentence explanation citing specific evidence>"}}

Where:
1 = Human (distinctive voice, genuine conviction, specific content — even if polished)
2 = Uncertain (mixed signals that genuinely could go either way)
3 = Likely AI-generated (formulaic, generic, no distinctive voice or specific content)

Transcript:
{sample}"""},
        ],
    )
    result = json.loads(resp.choices[0].message.content)
    score = max(1, min(3, int(result.get("score", 2))))
    return {"aiScore": score, "aiReasoning": result.get("reasoning", "")}


def summarize_sermon_content(input_data):
    """Generate a brief overview + key points from the transcript."""
    client = _openai_client()
    transcript = input_data["transcript"]
    words = transcript.split()
    sample = " ".join(words[:4000]) if len(words) > 4000 else transcript

    resp = client.chat.completions.create(
        model="gpt-5-nano",
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": "You summarize sermon transcripts concisely."},
            {"role": "user", "content": f"""Summarize this sermon transcript.

Return JSON:
{{"overview": "<2-3 sentence summary of the sermon's message and theme>", "keyPoints": ["<key point 1>", "<key point 2>", ...]}}

Include 3-6 key points — the main takeaways a listener should remember.

Transcript:
{sample}"""},
        ],
    )
    result = json.loads(resp.choices[0].message.content)
    return {"sermonSummary": {"overview": result.get("overview", ""), "keyPoints": result.get("keyPoints", [])}}


def download_rss_audio(input_data):
    """Download audio from RSS enclosure URL and upload to blob storage."""
    import requests as http_requests
    from azure.storage.blob import BlobClient

    sermon_id = input_data["sermonId"]
    audio_url = input_data["audioUrl"]

    resp = http_requests.get(audio_url, timeout=300, stream=True)
    resp.raise_for_status()

    ct = resp.headers.get("Content-Type", "audio/mpeg")
    ext_map = {"audio/mpeg": ".mp3", "audio/wav": ".wav", "audio/mp4": ".m4a", "audio/x-m4a": ".m4a"}
    ext = ext_map.get(ct.split(";")[0].strip(), ".mp3")
    filename = f"rss-episode{ext}"
    blob_name = f"{sermon_id}/{filename}"

    audio_bytes = resp.content
    if len(audio_bytes) > 100 * 1024 * 1024:
        raise ValueError("RSS audio too large (>100MB)")

    blob = BlobClient.from_connection_string(
        os.environ["STORAGE_CONNECTION_STRING"], "sermon-audio", blob_name
    )
    blob.upload_blob(audio_bytes, content_type=ct.split(";")[0].strip())
    log.info(f"[download_rss_audio] {sermon_id}: downloaded {len(audio_bytes)} bytes from {audio_url}")

    return {"blobUrl": blob_name}
