"""Miscellaneous activities: update_sermon, AI detection, content summary, RSS download."""

import json
import logging
import os

from activities.helpers import _openai_client, _cosmos_client

log = logging.getLogger(__name__)


def update_sermon(input_data):
    """Patch a sermon document in Cosmos DB with etag check."""
    container = _cosmos_client()
    sermon_id = input_data["sermonId"]
    updates = input_data["updates"]

    try:
        doc = container.read_item(sermon_id, partition_key=sermon_id)
    except Exception as e:
        if "NotFound" in type(e).__name__ or "CosmosResourceNotFoundError" in type(e).__name__:
            log.error(f"[update_sermon] {sermon_id}: not found in Cosmos")
            return {"ok": False, "error": "not_found"}
        raise

    etag = doc.get("_etag")
    doc.update(updates)

    try:
        kwargs = {}
        if etag:
            from azure.core import MatchConditions
            kwargs["etag"] = etag
            kwargs["match_condition"] = MatchConditions.IfNotModified
        container.upsert_item(doc, **kwargs)
    except Exception as e:
        if "PreconditionFailed" in type(e).__name__ or "412" in str(e):
            log.warning(f"[update_sermon] {sermon_id}: etag mismatch, re-reading and retrying")
            doc = container.read_item(sermon_id, partition_key=sermon_id)
            doc.update(updates)
            container.upsert_item(doc)
        else:
            raise

    return {"ok": True}


def detect_ai_generation(input_data):
    """Detect if transcript was AI-generated. Returns {"aiScore": 1|2|3, "aiReasoning": str}."""
    client = _openai_client()
    transcript = input_data["transcript"]
    words = transcript.split()
    sample = " ".join(words[:3000]) if len(words) > 3000 else transcript

    resp = client.chat.completions.create(
        model="gpt-5-nano",
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": "You are an AI-generated text detector analyzing sermon transcripts."},
            {"role": "user", "content": f"""Analyze this sermon transcript and determine if it was likely written/generated by AI or spoken by a human.

Consider these signals:
- AI text tends to be overly polished, formulaic, and lacks natural speech patterns (filler words, self-corrections, tangents, false starts)
- Human sermons have verbal tics, repetition, audience interaction, spontaneous asides
- AI text often has unnaturally even paragraph lengths and predictable structure
- Human speech has varying sentence complexity and natural rhythm breaks
- AI tends toward generic platitudes; human preachers have distinctive voice and style

Return JSON:
{{"score": <1|2|3>, "reasoning": "<1-2 sentence explanation>"}}

Where:
1 = Clearly human-delivered (natural speech patterns, verbal tics, organic flow)
2 = Uncertain (mixed signals, could be either, or heavily edited human speech)
3 = Likely AI-generated (formulaic, overly polished, lacks human speech markers)

Transcript:
{sample}"""},
        ],
    )
    result = json.loads(resp.choices[0].message.content)
    score = max(1, min(3, int(result.get("score", 2))))
    return {"aiScore": score, "aiReasoning": result.get("reasoning", "")}


def summarize_sermon_content(input_data):
    """Generate a brief overview + key points from the transcript."""
    client = _openai_client()
    transcript = input_data["transcript"]
    words = transcript.split()
    sample = " ".join(words[:4000]) if len(words) > 4000 else transcript

    resp = client.chat.completions.create(
        model="gpt-5-nano",
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": "You summarize sermon transcripts concisely."},
            {"role": "user", "content": f"""Summarize this sermon transcript.

Return JSON:
{{"overview": "<2-3 sentence summary of the sermon's message and theme>", "keyPoints": ["<key point 1>", "<key point 2>", ...]}}

Include 3-6 key points — the main takeaways a listener should remember.

Transcript:
{sample}"""},
        ],
    )
    result = json.loads(resp.choices[0].message.content)
    return {"sermonSummary": {"overview": result.get("overview", ""), "keyPoints": result.get("keyPoints", [])}}


def download_rss_audio(input_data):
    """Download audio from RSS enclosure URL and upload to blob storage."""
    import requests as http_requests
    from azure.storage.blob import BlobClient

    sermon_id = input_data["sermonId"]
    audio_url = input_data["audioUrl"]

    resp = http_requests.get(audio_url, timeout=300, stream=True)
    resp.raise_for_status()

    ct = resp.headers.get("Content-Type", "audio/mpeg")
    ext_map = {"audio/mpeg": ".mp3", "audio/wav": ".wav", "audio/mp4": ".m4a", "audio/x-m4a": ".m4a"}
    ext = ext_map.get(ct.split(";")[0].strip(), ".mp3")
    filename = f"rss-episode{ext}"
    blob_name = f"{sermon_id}/{filename}"

    audio_bytes = resp.content
    if len(audio_bytes) > 100 * 1024 * 1024:
        raise ValueError("RSS audio too large (>100MB)")

    blob = BlobClient.from_connection_string(
        os.environ["STORAGE_CONNECTION_STRING"], "sermon-audio", blob_name
    )
    blob.upload_blob(audio_bytes, content_type=ct.split(";")[0].strip())
    log.info(f"[download_rss_audio] {sermon_id}: downloaded {len(audio_bytes)} bytes from {audio_url}")

    return {"blobUrl": blob_name}
